### ISSUE TITLE
Winamp backend - Artist and Title are reversed

### ISSUE THREAD

**Issue by raekuul** [dlrudie/Snip#106]
In winamp.cs:74-77
`string artist = windowTitle[0].Trim();`
`string songTitle = windowTitle[1].Trim();`
`TextHandler.UpdateText(songTitle, artist);`
This has the effect of reversing songTitle and artist when following the included instructions to use ATF string %title% – %artist%. Please either reorder the strings or adjust the instructions.

**Comment by dlrudie** [comment]
I'll look into this.

**Comment by kaimi** [comment]
This is like a 2 minutes fix. I’d do it, but respones to pull requests seems a little slow here :)

**Comment by dlrudie** [comment]
After reviewing this the code I wrote was intentional.

The format of artist/title in the titlebar was for parity between Spotify and the rest.
The output text always shows "Title" - Artist (but you can rearrange this in output format).

Ideally I wouldn't want to waste any more time on Winamp or foobar in their current form. I just added grabbing the song from the titlebar as a way of getting player support in trivially. Future focus is better spent on implementing a way to communicate with Winamp's or foobar's API directly.
