### ISSUE TITLE
snip vanishes from taskbar

### ISSUE THREAD

**Issue by needtoscribble** [dlrudie/Snip#108]
Hi, I recently did a clean install of Win10 Pro 64bit and reinstalled Snip(I was using 32bit previously and it had worked fine).  It installed .NET Framework 4.6.1 in the process.  I even turned off my antivirus progs(Avast and Malwarebytes) before installing Snip and also later when trying to run to double check, including running as admin.

When I first load Snip it pops up in the taskbar but does nothing even with Spotify on, and in fact will vanish from the taskbar the moment I hover over it with my mouse. Help please? I really liked this program and I have no idea what to do it fix it.  No errors pop up at all, it just closes.

**Comment by viktae** [comment]
Same issue. W10 64bits...

**Comment by artman41** [comment]
do you mean the program is in the icon bar? (The bottom right)

If you can't see it, try and click the upwards arrow to see all the icons (^) and it should be there. Right click to see the options.
![snip win10 proof](https://cloud.githubusercontent.com/assets/5568965/17418996/4f27cdfe-5a93-11e6-96a8-d6e14e553ebe.PNG)

**Comment by needtoscribble** [comment]
No, it seems to crash and close immediately and remove itself from the active programs/applications and disappears from the task bar.  It gives no errors through windows or even itself, it just closes the moment you hover over it and never loads the program completely to even bring up a menu on right click.  I guess its stalling out on loading?  I even tried not hovering over it.  It lists it in running applications for a split second after clicking on the ap file, then closes.  As far as it has gone for me is to give the 'No Track Playing' text on hover before it crashes but usually its before that point.

I have actually wiped my comp since that first post and did another clean install and the problem persists.

**Comment by dlrudie** [comment]
Are you extracting the archive to its own directory and then running it? Or are you running it from inside of the archive?

**Comment by needtoscribble** [comment]
Directly into a new directory and no files exist on the drive of the previous versions.

**Comment by dlrudie** [comment]
Check your event viewer and see if there's any specific details it mentions about Snip in there.

**Comment by carolxann** [comment]
Same issue as described above, and I can see error reporting regarding Snip in the event viewer. What information would you like?

This is what I can dig out from the .NET runtime error:

> Application: Snip.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.UnauthorizedAccessException
   at System.IO.__Error.WinIOError(Int32, System.String)
   at System.IO.FileStream.Init(System.String, System.IO.FileMode, System.IO.FileAccess, Int32, Boolean, System.IO.FileShare, Int32, System.IO.FileOptions, SECURITY_ATTRIBUTES, System.String, Boolean, Boolean, Boolean)
   at System.IO.FileStream..ctor(System.String, System.IO.FileMode, System.IO.FileAccess, System.IO.FileShare, Int32, System.IO.FileOptions, System.String, Boolean, Boolean, Boolean)
   at System.IO.File.InternalWriteAllBytes(System.String, Byte[], Boolean)
   at System.IO.File.WriteAllBytes(System.String, Byte[])
   at Winter.MediaPlayer.SaveBlankImage()
   at Winter.MediaPlayer.Unload()
   at Winter.Snip.ToggleSpotify()
   at Winter.Snip.LoadSettings()
   at Winter.Snip..ctor()
   at Winter.Program.Main()

**Comment by dlrudie** [comment]
Snip shouldn't _need_ to run as administrator, however if the directory it's placed in requires administrator access it may be necessary.

**Comment by dlrudie** [comment]
I'm going to say this has been fixed.
