### ISSUE TITLE
output format issue/question.

### ISSUE THREAD

**Issue by murko69** [dlrudie/Snip#119]
Before 5.5.0 I could use html tag in these boxes without any problems,
Did the new features/fixes (new hidden $i variable maybe) have anything to do with this not working now?

I used images (icons) in front of artist/track/album like:
`<img alt="" height="18px" src="../spotify/np_song.png" title="Song" width="18px" /> $t
<img alt="" height="18px" src="../spotify/np_artist.png" title="Artist" width="18px" /> $a
<img alt="" height="18px" src="../spotify/np_album.png" title="Album" width="18px" /> $l`

And this worked fine on 5.4.0. It doesn't anymore. I don't get any errors, but it looks as if only the actual variable is fetched from Snip.
Simple reason I did it like this was that the icons also disappeared when Spotify was offline and that (IMO) looked better
See attached screen shot! (the last part with the head phones was a test before the hidden $i variable was introduced)

![080 - mmss](https://cloud.githubusercontent.com/assets/12071221/18815154/526be410-8328-11e6-96bd-da71960af0c8.png)

**Comment by dlrudie** [comment]
Nothing should have changed in that regard. What does it do now?

**Comment by dlrudie** [comment]
Whenever there is a new version of Snip it uses default settings until you re-set everything.

I honestly can't recall why I use this behavior instead of just using/importing old settings. I'm sure there was a reason. :)

Anyway, make sure your output format is set accordingly after each new version.

I copied and pasted the string you have above into the track format box and erased the other three boxes. Using the above my Snip.txt file looks like:

<img alt="" height="18px" src="../spotify/np_song.png" title="Song" width="18px" /> Delay <img alt="" height="18px" src="../spotify/np_artist.png" title="Artist" width="18px" /> M|O|O|N <img alt="" height="18px" src="../spotify/np_album.png" title="Album" width="18px" /> Particles

**Comment by murko69** [comment]
Yes I also have that in **that** text file if I do what you do, but I have settings to "use separate files" and have always put the different outputs in spelarate fields aswell

But I do not get the images anymore and my output is set accordingly for each new version. I actually saved a textfile called output_format just in case since the old settings always disappear ;)

This is strange.

**Comment by murko69** [comment]
I will uninstall Snip when I get back home, and then re-install 5.4.0 and check if I still get it to work for separate files. And after that try and install 5.5.0 and do the same again, see if I did smething wrong the first time.
My settings looks fine AFAIK :/

**Comment by dlrudie** [comment]
Oh wait. I did change something.

https://github.com/dlrudie/Snip/commit/2747e2cb104713d1b488d210d962a0359c7308fe#diff-8ca081224765172e10a15d3f8eb32c1cL161

I changed that because I couldn't remember why I did that. I really need to comment my code more. :)

I can revert it.

**Comment by murko69** [comment]
Commenting code.... seems so unnecessary ;)
