### ISSUE TITLE
Wrong track title, album and artist with Spotify

### ISSUE THREAD

**Issue by jingtongtangflee** [dlrudie/Snip#126]
I just today notified, that Snip's sometimes showing wrong track title, album and even artist.
![bug](https://cloud.githubusercontent.com/assets/9393124/20245912/bd3dc7dc-a9ab-11e6-9751-c43faf7f4f34.PNG)
I'm using Snip v5.6.0

**Comment by dlrudie** [comment]
This will happen from time to time and there's not much I can do about it. When querying Spotify's servers I can only submit what's in Spotify's title bar. Because of this the result returned may not always match with what's actually being played. I do what I can to narrow down the result and choose the most accurate one but there will still be times it's just not right.
