### ISSUE TITLE
Album Art Empties Even When "Empty File" Option is Disabled

### ISSUE THREAD

**Issue by gch5074** [dlrudie/Snip#140]
So I disabled the option to "Empty File if No Track Playing", and it works great for the text fields, however the album art still disappears.  Should it be this way, or would it be possible to maintain the previous album art?

Thanks!

**Comment by dlrudie** [comment]
I don't understand.

The "empty files" option only applies to the .txt files. If you enable the option, which it is by default, it will erase the text in the .txt files if you stop or pause a track, or exit Snip. It does not touch the album art at all.

If the option is disabled, then rather than the text files being empty it will instead have text that says "No track is playing".


If you just want to keep all of the artwork just click on "Keep album artwork"
