### ISSUE TITLE
Album art not saving when song is paused / multiple artist not being displayed

### ISSUE THREAD

**Issue by Fuguu** [dlrudie/Snip#150]
As the title suggests, album art becomes a 1x1 pixel when spotify is paused but comes back when song is playing.

"Save Album Artwork" is enabled
"Empty file if not track is playing" is disable

Also when there is multiple artists on a track, snip will only grab the first one rather than all the artists.

**Comment by dlrudie** [comment]
Replacing the artwork with a 1x1 pixel when paused is by design. This is because when you pause it the Spotify window title goes blank, so it doesn't know whether you stopped the track or paused it.

The same with the artists. Snip just uses Spotify's own API to search for the track. So the results of one artist is actually Spotify's result, not Snip's.
