### ISSUE TITLE
Information Saving

### ISSUE THREAD

**Issue by Phineas** [dlrudie/Snip#161]
Hey,

I was wondering if you could implement a way to save information separately while also allowing us to keep the Song.txt file the same as set in the output format section?

Thanks!

**Comment by dlrudie** [comment]
What do you mean? It currently uses the output format and saves all files with whatever is set in the output format.

**Comment by murko69** [comment]
Maybe @Phineas is talking about the Snip_History.txt file?
If not then this is a separate request :)

I've saved output separately and included images in there, like:
`<img alt="" height="18px" src="../spotify/np_song.png" title="Song" width="18px" /> $$t
<img alt="" height="18px" src="../spotify/np_artist.png" title="Artist" width="18px" /> $$a
<img alt="" height="18px" src="../spotify/np_album.png" title="Album" width="18px" /> $$l`

When I use the option for file Snip_History.txt I would prefer if I could use the simple format "$$a - $$t" or maybe "$$a - $$t [$$l]" and strip the images (HTML) completely.
Also, if possible, I would like an option to add info in Snip_History.txt at the top (eg. descending order instead of ascending as is today).

This is because when and if I want to use this on my web page as "track history" I'm thinking of reading the top 10 lines from the history file and just present that. Maybe it's possible to take the last 10 rows aswell, and present them in an opposite order I don't know. I haven't really played around with that yet, I'm just thinking out loud :)

If this wasn't at all what OP ment, then I apologize :)

**Comment by dlrudie** [comment]
I do plan to eventually change how the output setup is. I've thought about making just one box that you can change how the output looks, but then it wouldn't know the difference between tracks, artists, or albums and saving specific outputs in those text files. The end result would just add a whole lot of individual settings and clutter.

I don't really have any plans to change how the history format is saved.

**Comment by murko69** [comment]
I'm pretty easy to persuade. Sounds legit and I don't really use the history to be honest. I just had a "what if" -moment :)
Just leave things as is..... :D
