### ISSUE TITLE
Snip won't fetch data of music from Spotify's local files section

### ISSUE THREAD

**Issue by Robdogga55** [dlrudie/Snip#174]
I have downloaded some MP3s and got Spotify to include them in the local files section of Spotify. When I play them Snip won't pick them up, however if I went to a song from Spotify it would be fine.

**Comment by dlrudie** [comment]
This probably won't work as Snip relies on Spotify-specific track ID's to gather data. Local files won't have track IDs. Also I don't even know how you got local files to work because I've never been able to play local files in Spotify. I can add local files to play but when I attempt to play them it just says the song isn't available.

**Comment by dlrudie** [comment]
If I can get local files to work on mine I'll try to see what metadata Spotify provides. I may be able to get some information,

**Comment by omfgblondie** [comment]
I've been trying to get Spotify to play local files for a few hours now and what solved it for me was this MP3 codec: http://www.free-codecs.com/mpeg_layer_3_codec_download.htm

**Comment by dlrudie** [comment]
See #224
