### ISSUE TITLE
Snip won't run Win 8.1

### ISSUE THREAD

**Issue by Vadatajs** [dlrudie/Snip#180]
It technically will open and run for a second, I see the icon in the system tray. As soon as I mouse over it or wait a few seconds it disappears and I am unable to use it.

Any ideas?

**Comment by dlrudie** [comment]
It's not 8.1-related as I'm on 8.1.

If the icon disappears something else went wrong. However there's not enough detail here to determine what.

Make sure Snip is extracted from the archive to its own folder. Try running it as administrator as well.

**Comment by murko69** [comment]
Sounds like a similar issue I had with a program called InfraRecorder, after I updated my computer from Win7 to Win10. Probably some sort of access denied issue. Some times it started but hovering the icon made it shut down and disappear and in order to start it again I had to kill all running processes in Task Manager and all that was "solved" by running as admin AFAIK.
