### ISSUE TITLE
Snip doesn't detect my song in spotify :c

### ISSUE THREAD

**Issue by Axiom12** [dlrudie/Snip#181]
"No track playing" is the message that appears in snip while a song is playing

**Comment by killerspaz** [comment]
I just found this app, but doesn't appear to be working at all with Spotify. I don't get anything within `Snip.txt`.

**Comment by dlrudie** [comment]
Make sure the Spotify web service is running. You may have to go to advanced options within Spotify.

**Comment by RogerRoger101** [comment]
"Make sure the Spotify web service is running. You may have to go to advanced options within Spotify" (spotify web service isn't an option any more under advance settings)

This is still an issue, "no track playing" with Spotify.  maybe this can be due to the NDI plugin? I wasn't having any issues until I installed that plugin so I can stream from another PC

**Comment by MeikelLP** [comment]
@RogerRoger101 see #315
