### ISSUE TITLE
Spotify - only empty files

### ISSUE THREAD

**Issue by fuba82** [dlrudie/Snip#189]
Hi there,  
Snip just generates "empty" text files and a empty jpeg.  
No matter what settings i change!
The Tray Icon Hint says "No Track Playing"
Also tried to run as Admin and restarted Spotify <> Snip.  

Just Hotkeys are working nothing else...

Snop version: 6.9.1
Spotify version: 1.0.60.492.gbb40dab8

**Comment by dlrudie** [comment]
If no track is playing then yes, the files will be empty. Need to figure out why no track is playing.

**Comment by q3fuba** [comment]
> If no track is playing then yes, the files will be empty. Need to figure out why no track is playing.
 👎 1  
Yeah...
It is not really worth to comment this...
But it is that useless so i need to do so :D

OF COURSE i do play a Song else it would not be a Bug ?!?! :D
Awesome...
Really awesome :P
You made my day 🤣

**Comment by murko69** [comment]
Maybe answer in #181 is your prefered solution @q3fuba ?

**Comment by q3fuba** [comment]
Does not work :/

SpotifyWebHelper.exe is running and everything seems to be active.
![image2](https://user-images.githubusercontent.com/11580974/29133918-4c2e72d6-7d35-11e7-94f9-50425d1e7540.png)

**Comment by murko69** [comment]
Strange.
If I toggle that one I get "no track is playing" when it's disabled and correct output when it's enabled. The only time I see this otherwise is if I play local files in Spotify. That don't work (no output) but otherwise it should work.
How's your settings (including output)?
Eg. 
![snipsettings](https://user-images.githubusercontent.com/12071221/29134430-e158362a-7d36-11e7-8b22-277cc65c086f.png)
