### ISSUE TITLE
Snip 6.9.1 freezes on Right-Click after starting

### ISSUE THREAD

**Issue by Maddosaurus** [dlrudie/Snip#210]
Just noticed something interesting.
My environment: Windows 10 x64, Spotify Desktop, Snip 6.9.1 (latest).

The right click menu is non-responsive under the following conditions:

- Having Spotify selected as source
- Start Snip before Spoify
- Right-Click the Snip-Icon in the Icon Area
 - Observe freezing right click menu (as in: the cursor indicates a non responding window)

This, interestingly enough, can be fixed by starting Spotify and play some music.   
I don't know if this corner case is interesting for anyone or worth fixing.  

Have a nice day!

**Comment by recon88** [comment]
Can confirm. Same happening to me.

**Comment by dlrudie** [comment]
I've known about this. It hangs because it's trying to find SpotifyWebHelper. And until it does it blocks the rest of the application. I made a multi-threaded version before where it didn't hang but I didn't feel comfortable with the results so I opted to have it freeze momentarily until I came up with a better solution. It's a work in progress. :)

**Comment by jhobz** [comment]
Wanted to add to this that if I waited long enough it would stop freezing/crashing, but the menu options would not be clickable (clicking in the context menu would make the default Windows "error" sound). Frustrating since I don't use Spotify and appear to have no way to switch to GPMDP without straight up downloading Spotify...

**Comment by jhobz** [comment]
Ok after long enough a textbox about a hotkey already being registered showed up and then I got control again... so no idea why it took so long for that to show up, but eventually it did.

**Comment by RaspberryKitty1** [comment]
This is a good program to use during my streams but I have same issue. When i want to test on my free time it freezes. (Spotify is blocked on the Wi-Fi I'm using right now) but I do have Premium account on Spotify.

**Comment by dlrudie** [comment]
Fixed in v6.9.5.
