### ISSUE TITLE
Feature support for Music Groove(Zune) Win10?

### ISSUE THREAD

**Issue by Happiys** [dlrudie/Snip#229]
For me it easy just to use music groove load 3 seconds in and done play selected playlist and done but I don't know iTunes just take 34 years to load then has an update. Google Play Music Desktop is buggy and doesn't place my music in the playlist. VLC takes a while load from track to track and sometimes crashes. Winamp seems to complicated and Foobar2000 seems sketchy. Quod Libet freezes after like 5 tracks played. I don't see why not make it compatible for a built in music player that doesn't give me ads (GPMD, Spotify). And wondering why this wasn't like a first on thing with others.

**Comment by markspolakovs** [comment]
As far as I can tell, there is **no way** to programmatically get the currently playing track from Groove. For the time being, at least, Groove integration seems impossible to me. Sorry.

**Comment by dlrudie** [comment]
To be fair... I personally use Spotify and iTunes. I wrote Snip originally for my own use. In fact I gave the name Snip as a play on "Spotify iTunes Now Playing". After awhile I decided others might want to use it and released it to the public. I've added some support for other players here and there based on ease of adding them in, but it was never really my intention to provide a program that supports everything ever out there.

Now I've never looked into Groove but needless to say my time is very limited at the moment. You're more than welcome to add support if you'd like.

**Comment by markspolakovs** [comment]
@dlrudie What would your thoughts be on a pluggable interface for other players? So that you can download support for other players as a .dll, instead of all of them being supported in the base app?

**Comment by dlrudie** [comment]
While it's not a bad idea I don't think of it as a solution either. I have a plugin interface in one of my other applications. You can add/remove DLL's for things you'd like support for. The problem is that it's not really useful. It would add a lot of overhead for something that really isn't an issue to be built in. Yes, you'd be able to make a plugin without having the source for Snip (but it's open source anyway). But then I'd have to create API documentation, add support so API's are versioned so there's no version incompatibility, risk people running old versions of plugins, etc.

Snip just isn't large enough in my mind to warrant a whole plugin interface. I'm not opposed to it. I just don't feel like it's worth the effort at the moment. As the code sits right now it's not difficult to create a new media player source code.

**Comment by dlrudie** [comment]
See #263
