### ISSUE TITLE
album artwork changes sizes even on the same song it was scaled to.

### ISSUE THREAD

**Issue by phaeling** [dlrudie/Snip#247]
So if i play song x and set the size in obs the way i like it. the next song might be the same size and all is fine. or it may not and scale the obs frame a different size. then when song x plays again its scaled to the changed size.

im not sure if you will understand what i am trying to explain. but if it has something to do with the sources  being different sizes how come song x shows as different size next time it plays? also a fix for this would be an option to possible force a image dimension size for the output file?

**Comment by dlrudie** [comment]
I don't do any image scaling whatsoever. Spotify provides three different artwork sizes. Depending on your selection it just downloads a small, medium, or large size artwork that Spotify provides. What Spotify provides may not always be the same resolution as each other. There's nothing I can do about this short of implementing an image resizing method and I'm not going to do that.

Now something to consider is that while an artwork file is being downloaded, or if there's any issue getting artwork whatsoever, then a small transparent 1x1 png image will be saved. Perhaps the problem comes from it scaling down for the 1x1 image and the next time it plays it creates a larger image?

I couldn't say for sure. The way I set up my images in OBS I just use image source and specify the file. I drag and shrink the box to where I want it. After that everything just works as it should.
