### ISSUE TITLE
Spotify Local Files Ignored

### ISSUE THREAD

**Issue by bluespark23** [dlrudie/Snip#249]
Hi Guys,
something weird has recently started happening in my setup.  Snip gets the metadata correctly for all spotify songs. however any tracks in "Spotify local files" are totally ignored. This definitely worked for many years until just recently.  I have checked the tags of my local files in MP3Tag and everything seems to be correct. Has anyone else experienced this ? Is it a known issue?
Does anyone have a fix or a workaround?

**Comment by dlrudie** [comment]
I know about this but I don't know about this. I've never been able to get Spotify to play local files for me.

The reason it doesn't work anymore is because I used to get the song information from the window title of Spotify and search for it. Currently I connect to Spotify directly to pull information and it may not provide enough details to get the song information from Spotify's servers. I need to get local files working on my Spotify and check the metadata Spotify provides to see if I can still get information about the track.

**Comment by bluespark23** [comment]
Hi David,
Thanks for the reply!

When Spotify plays a local file, as long as the MP3 file has the correct tags, it shows up in Spotify correctly – in the playlist and now playing panel bottom left.

The file plays perfectly,  just doesn’t  seem to come to snip any more. – I am guessing Spotify changed their code again...

I was working fine in snip 6.9.1 until a recent update to Spotify.

I make a folder which I point to from Spotify specifically, from Settings, Local Files – for example U:\local files

I add this SOURCE and switch the default ones off.

Delete the mp3 from that folder and it disappears from Spotify local files

Cheers!

Sparky



Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
