### ISSUE TITLE
Snip's Hotkeys stopped working for Spotify

### ISSUE THREAD

**Issue by shdshdw** [dlrudie/Snip#255]
Spotify stopped responding to keyboard shortcuts since 3 days. I have made sure that the "Enable Hotkeys" option is checked. Snip is still able to connect to Spotify and show the song that is being played. This issue occurred on a Windows 10 system with no other programs interacting with spotify or keyboard shortcuts.

**Comment by idk** [comment]
Same issue here

**Comment by SilverainStudios** [comment]
I was using an app called Toastify for hotkeys and track info, but over a week ago it stopped working. It told me that "Spotify was unavailable", and would not work no matter what I tried.
I downloaded this, hoping for a substitute, but while it shows the track info the hotkeys are unresponsive.

So it appears that a recent Spotify update broke something. Great.

**Comment by dlrudie** [comment]
It would appear that Spotify player no longer accepts media keys for control. I can send commands through SpotifyWebHelper but I'll have to add that support separately.

**Comment by GenesisFR** [comment]
I know why this happens, the handle is no longer retrieved in Spotify.GetSpotifyWindowHandle(), I fixed it locally, now if only the rest of my Snip was working...

**Comment by dlrudie** [comment]
But... it does get the handle there.
It literally says that.
However. Thanks for looking into this because there was a problem there.
Snip used to look for SpotifyMainWindow as that was the window class of Spotify.
Spotify has since changed it from SpotifyMainWindow to Chrome_WidgetWin_0.
I've updated this locally and hotkeys work again.

**Comment by GenesisFR** [comment]
I used Spy++ to look for the window handle but I was using "Chrome_RenderWidgetHostHWND" which wasn't retrieving the handle.

I opted for this solution, however it wasn't working when Spotify was minimized in the taskbar.

`private void GetSpotifyWindowHandleNew()
{
    Process[] processes = Process.GetProcessesByName("Spotify");

    foreach (Process proc in processes)
    {
        if (proc.MainWindowHandle != IntPtr.Zero)
            this.Handle = proc.MainWindowHandle;

        proc.Close();
    }

    this.spotifyWindowFound = this.Handle != IntPtr.Zero;
}`

Your method is better because it's able to retrieve the handle even when Spotify is minimized in the taskbar.

**Comment by dlrudie** [comment]
Spy++ does indeed show the handle you're talking about but it's just a child handle. The parent window handle to it is Chrome_WidgetWin_0.
