### ISSUE TITLE
Spotify Not Running

### ISSUE THREAD

**Issue by Chrionz** [dlrudie/Snip#283]
So, whenever playing spotify, it just goes blank with the album art and track if I have emptying the file enabled and a message that says "Spotify is not currently running." Problem is, It is running and does it partway through a song. However, when a new song comes on it does the same thing. Shows the info and art for a bit, then stops. Tried re-installing spotify and snip, still no luck

**Comment by triedthisonline** [comment]
Just curious, do you have a game launcher (like Steam, Battle.net, etc.) open while testing if it works? 

I've only had this issue while playing a game, works just fine if I'm just streaming with a cam which sort of defeats the purpose since I mostly stream gameplay and am guessing it's the same for others with this issue. Hope someone can figure it out, works great when it works! hah 🤣

**Comment by BrandonDocDC** [comment]
Updated Windows and Spotify, getting either "Not song is playing" or "Spotify is not currently running" error when Spotify is not only running but it is also playing a song....

**Comment by murko69** [comment]
@BrandonDocDC Sometimes a simple restart of Spotify and/or Snip might be necessary. Getting that sometimes as well.

**Comment by Chrionz** [comment]
@murko69 No matter what it does it. It will be good for half a song, then stop.

**Comment by Vierdz** [comment]
This issue still persists for me, the Snip.txt file is empty.

**Comment by dlrudie** [comment]
See #299
