### ISSUE TITLE
Spotify part of Snip not working any more with new Spotify update

### ISSUE THREAD

**Issue by TheSqrtMinus1** [dlrudie/Snip#300]
title.

cant provide any logs or whatever because i dont know where they are or if they even exist, sorry

tried restarting computer, restarting snip, and restarting spotify, all in various orders, nothing resolves the "no track playing" message with Snip.

any fix?

**Comment by TheRylez813** [comment]
I am also having this problem.

**Comment by neverbackdown81** [comment]
im also haveing the problems snip latest version wont do anything now just says no track playiing even tho spotify is running

**Comment by Florenzius** [comment]
Same problem. Please fix!

**Comment by pswaab** [comment]
Hi Same here,

After spotify updated it seems not working anymore, so probably something closed by Spotify.
Hopefully there will be a fix soon.

Kind regards Patrick

**Comment by Levadio** [comment]
same problem fix it pls

**Comment by TheSqrtMinus1** [comment]
#300 is a dupe of #300? lol

**Comment by TheSqrtMinus1** [comment]
anyway closing and saying for any other future visitors: go to #265

**Comment by markspolakovs** [comment]
@TheSqrtMinus1 I think I meant to comment this on 301, oops.

In general though, there's no point in opening a new issue just because it doesn't work *for you* if there are at least four other people reporting the exact same problem - for the developer it's just duplicate information, and they waste time reading through issues of people reporting the same thing in the hope that there's some new information. "me too pls fix" is the most useless comment one could ever post on an issue. The developer - and everyone who's commented on it - gets an email, they check if in the hope of there being new information that could help diagnose the problem and fix it, but they only get frustrated.

My sincere apologies if I seem harsh, however I hope you get where I'm coming from.
