### ISSUE TITLE
Spotify Issues

### ISSUE THREAD

**Issue by DiegoTheMod** [dlrudie/Snip#306]
Spotify's latest update broke Snip so it can no longer read the track and author for an output.

**Comment by uncajesse** [comment]
I updated from v6.9.5 to v6.10.1 (because Spotify), elevated via UAC, and I'm getting a bug as well with it.

I already had Spotify running, and Snip's status text was stuck on "Switched to Spotify" without changing. I restarted Snip a half dozen times, switched between players etc, changed track, etc.... and same thing.

Then I tried running Snip first, then running Spotify, and that worked. It also fixed the bug I was experiencing before, even when running Snip after Spotify.

**Comment by DiegoTheMod** [comment]
Yes i am running 6.10.1 but I will try running Snip first then Spotify. 

Diego

**Comment by dlrudie** [comment]
Which version of Windows are you on? Are you using a 32-bit OS or 64-bit OS?

**Comment by uncajesse** [comment]
Windows 7 x64 SP1 (6.1.7601) "Ultimate" flavor

**Comment by Tanyn2678** [comment]
Mine doesn't even recognize Spotify is playing. :(

**Comment by murko69** [comment]
Snip doesn't work for me no matter what version I try.
Last working one was 6.9.1. but since that stopped working I've tried all new releases (last one 6.10.1)
Still got "no-track-issue"
I'm still running on Windows 10 **32-bit** though so I'm guessing that's my issue?!

**Comment by RSammartano01** [comment]
I was having this issue yesterday, but suddenly it just started working

**Comment by DiegoTheMod** [comment]
It started working today. Idk whats up with it.

**Comment by uncajesse** [comment]
> It also fixed the bug I was experiencing before, even when running Snip after Spotify.

Actually it didn't fix it long term.

In order to get it to work, I have to start Spotify first, and then Snip. Then I can restart Snip and it still works.

If Snip is running when Spotify starts, it doesn't work even after restarting.

100% repeatable here. Let me know if I can help. :) I'll be around, in my studio [working](http://stream.masterfulaudio.com:7911/Omnia9fm.mp3.m3u) Mon/Tue. I might have a look at the sauce as well. :)

**Comment by RSammartano01** [comment]
Yeah that seems to work for me fine @uncajesse , thanks

**Comment by dlrudie** [comment]
I may not have tested it thoroughly in all orders of opening/closing certain programs. I'll test everything out when I'm off work. Updates may be delayed throughout the week as I work 12-hour shifts M-F, and certain Saturdays. I'll get to it tonight though.

**Comment by dlrudie** [comment]
I haven't been able to duplicate this. If I have Spotify running first and I launch Snip, it will say "Switching to Spotify" but after a second or so it picks it up and says No track playing.

**Comment by GenesisFR** [comment]
I noticed I also have the same bug than @uncajesse sometimes, usually after a fresh reboot.

Here's what the variables were like.

![image](https://user-images.githubusercontent.com/3614449/43154287-d98d1960-8f41-11e8-9454-07b09b0924c7.png)

Apparently, the parent ID (6820) of Spotify was Windows Explorer in this case. which could explain why it's not working.

![image](https://user-images.githubusercontent.com/3614449/43154967-0333e36e-8f44-11e8-8320-d1d09ae8ec2b.png)

**Comment by dlrudie** [comment]
Interesting. I'll take a look at that. How did you launch Spotify? Did you double-click it from Explorer? Did you launch it through a shortcut?

This could be a simple fix. I just need to verify that the parent process is also spotify.exe. If it's not then we're already at the parent process.

**Comment by GenesisFR** [comment]
I launched it from the pinned icon in my taskbar.

**Comment by dlrudie** [comment]
Currently it just assumed that the process found would be a child process and it would automatically grab the parent process. But if the parent process turns out to be explorer or something else then that messes it up. I'm working on a solution.
