### ISSUE TITLE
Unable to use app without authorizing Spotify

### ISSUE THREAD

**Issue by UVClay** [dlrudie/Snip#369]
When first launching Snip, if you close the Spotify authorization window that shows up (which I did, as I don't use Spotify) you get no context menu when right clicking the application.  Had to kill it through Task Manager.  I tried it another time and got the same result, so I created a Spotify account and authorized Snip and now it works just fine.

**Comment by dlrudie** [comment]
Thanks. I’ll look into this. I hasn’t looked at that aspect.

**Comment by FoxCutter** [comment]
I have this issues myself, not having spotify means that I can't use the new version of the app at all, so I'm stuck with the older version until it's fixed.

**Comment by FoxCutter** [comment]
Okay, I have a workaround for this.

1. Run Regedit.exe
2. If it doesn't already exist, create a new key called "Snip" Under HKEY_CURRENT_USER\Software 
3. Under that Created a new key called "7"
4. Under "HKEY_CURRENT_USER\Software\Snip\7" created a new DWORD value, with the name "Player"
5. Set it to 1

![Untitled](https://user-images.githubusercontent.com/19558800/69906576-57e84880-137a-11ea-92dc-b77566e3a2e2.png)

This will cause Snip to start up with iTunes instead of Spotify.

**Comment by dlrudie** [comment]
Fixed with cd419788b43b5c62512f4c29d9641b7ae8af92c2
