### ISSUE TITLE
Snip always request spotify autorization

### ISSUE THREAD

**Issue by Triton707** [dlrudie/Snip#375]
Every time i open snip, it opens a chrome tab to request the spotify autorization for my account.
The first time i upgraded it to 7.0.2 it worked, but now every time i try to launch snip it will open a new chrome tab and try to connect to the spotify autorization page, but it returns me this error
"ERR_CONNECTION_RESET"
I tryed everything is on the internet to resolve this problem but i can't figure it out.
The app still works great but is annoing that every time i launch the program this happen

(sorry for any mistakes i am an italian guy with some minor english skills XD)

![Cattura](https://user-images.githubusercontent.com/53498432/62173429-53f9da80-b336-11e9-9e17-ec459c8e3446.PNG)

**Comment by dlrudie** [comment]
What method do you use to authenticate? Spotify account? Or Facebook?

**Comment by HoboSnacksTV** [comment]
In the same vein as this issue, is there a way to stop Snip from opening a Chrome tab upon each launch? I authorized it with Spotify and it works (the tab basically just says it's authorized), but the tab opening every time is a bit undesired. I can move this comment to a new thread if this is unrelated.

**Comment by tigeus** [comment]
Got the same issue. :( Opens an opera "localhost" window every time I open Snip.

**Comment by Triton707** [comment]
I used spotify to autenticate, my problem is the same as @tigeus

**Comment by dlrudie** [comment]
The new browser window is unavoidable due to the way authentication works with Spotify. They require accessing their website and then it redirects back to a local web server to provide a code used to exchange for a token. It’s completely normal.

However the error isn’t. I’m guessing that has to do with the local web server being unable to start or maybe the computer is too slow and the local server times out and shuts down before the callback is complete.

**Comment by Triton707** [comment]
So from this new version every time I launch snip it will open that chrome tab?

**Comment by dlrudie** [comment]
I was typing a reply but GitHub on mobile erases everything automatically if you tap out of the text box.

It will open a new tab/window each time.

**Comment by Triton707** [comment]
And there is no way to avoid this? I use snip to put song information on my stream and I have to launch the application many times during the stream, and having a chrome tab always open up is really annoying

**Comment by dlrudie** [comment]
Currently there is no way to avoid this.

You shouldn’t have to restart Snip once it’s running. I’ve left it open for days and it still works.

I understand it’s annoying but currently it is out of my control due to the way Spotify handles authorization. I’m trying to come up with a workaround but no ETA on when I’ll have it. I work 80 hours a week and my time is limited.

**Comment by jarentrux** [comment]
If you are having localhost error then;

right click snip
select itunes
select spotify back

done :)
