### ISSUE TITLE
Track info not working

### ISSUE THREAD

**Issue by ItsMadaleine** [dlrudie/Snip#431]
I'm using OBS Studio, and I have the current version, however, when I try to set up Snip, the track info is blurry. When it loads, it starts so big that it takes up most of the screen and if I try to adjust the size, it causes the font to change. I've tried various fonts but nothing seems to work. I haven't used SNIP in about a year because I was having issues with it (never loaded). I'm not sure how to change get it to work. I'd also like it to scroll, but that doesn't seem to work either.

**Comment by GenesisFR** [comment]
Your problem is not related to Snip so it's not the right place to ask.

However, here are my text source settings in OBS, never had a single issue in years:
![image](https://user-images.githubusercontent.com/3614449/87943969-c47c9880-ca6c-11ea-81d9-dc7ba1fa7d58.png)
![image](https://user-images.githubusercontent.com/3614449/87944072-eb3acf00-ca6c-11ea-98f7-bf1cab290d57.png)
![image](https://user-images.githubusercontent.com/3614449/87944006-d2321e00-ca6c-11ea-9b41-c051dd3bfb4d.png)

**Comment by ItsMadaleine** [comment]
My apologies! It's my first time commenting here. Thank you for your help!
