### ISSUE TITLE
Spotify now supports local files cover art, could Snip do it as well?

### ISSUE THREAD

**Issue by monsieurmv** [dlrudie/Snip#433]
Hello! Everything is in the title. I've recently (my bad if it isn't that recent) noticed that I see cover art in the bottom left corner of Spotify when playing local files. This information however does not translate to Snip displaying it. It'd be awesome if that could be done, and would encourage me using a lot more local files on stream!

Thanks for all the work 👍 
![image](https://user-images.githubusercontent.com/68876408/88594561-afea6280-d061-11ea-82d9-670969d8f5fb.png)

**Comment by krimtsev** [comment]
Use this https://prnt.sc/ttf38r

**Comment by daameerstone** [comment]
First - thanks for the great program!

I think the problem is the same for me when playing local files in spotify and artwork:
- in case local song is played first there is no album art at all
- in case i played a song from Spotify its album art stays along the local song being played.

Example is image below where album art of Prodigy Wild Frontier stays when my local song is played after it.
![album art](https://user-images.githubusercontent.com/69280070/89474061-d48eba80-d784-11ea-90ef-f3da488b888d.jpg)

Spotify does recognize the album art as you can see below
![album art spotify](https://user-images.githubusercontent.com/69280070/89474227-4d8e1200-d785-11ea-9187-c6a6f736f11e.jpg)

I did try what kimtsev suggested and checked to save album art, didn't work.

**Comment by Jwguy** [comment]
Yeah, can definitely back this up: Snip doesn't seem to save artwork for local files.

It'd be cool if it did.

**Comment by dlrudie** [comment]
I'll check this out at some point.

**Comment by Sickolas** [comment]
Just wondering if you have gotten around to this, I cannot get it to show the album art for local songs either, even though the spotify app shows them just fine.

**Comment by BrillMatic** [comment]
Snip detects local album artwork on iTunes but not for Spotify. Not the exact solution but it's a workaround for anyone with this problem.

**Comment by dlrudie** [comment]
I will be working on local file support soon.

**Comment by dlrudie** [comment]
For self reference later on - https://developer.spotify.com/documentation/general/guides/local-files-spotify-playlists/

**Comment by dlrudie** [comment]
So experimenting with this I can get Snip to display the artist/album info for local files, even when Snip is running remotely, but Spotify's API does not provide any way to retrieve the artwork of local files.

To get around this would involve quite a lot of extra work. I'd have to either:

A) Implement an ID3 tag reading library directly into Snip for processing MP3 files which would require even more work to even find the MP3 file as the Spotify API doesn't actually provide a file path to the MP3.

B) Take the reported artist, album, and track names from the metadata and then use Spotify's search API to locate a match from those. This will always provide mixed results as the search can return anything and there's no way to accurately verify what was returned matches what is playing.

Snip now successfully reports local files (albeit untested with incomplete or missing ID3 tags) as of commit 0068da4615ddc293fb5adcd471dbe3077444ac65 but as of right now there is no way to save the artwork without an _extensive_ amount of work.
