### ISSUE TITLE
Run snip from streaming pc and spotify from main one

### ISSUE THREAD

**Issue by karsaidavid** [dlrudie/Snip#440]
Is it possible to run snip from streaming pc and spotify from main one? 
I'm not getting spotify login promt when i try to run snip from streaming pc.
Any tips on what im doing wrong?

**Comment by MalicT** [comment]
Snip has to see Spotify to be able to take the song that is playing and write it to a text file.

**Comment by karsaidavid** [comment]
Do you think it's possible to have two instances running on both of the pc's and have the main one selected as playback device while the playback is synced between the two? 
So basically the spotify instance from the streaming pc is only needed for the playback info.

**Comment by GenesisFR** [comment]
You can have Snip and the Spotify desktop player on your streaming PC then use the Spotify web player from your gaming PC, however you won't hear the songs as they'll be playing on your streaming PC.

**Comment by dlrudie** [comment]
I stream to a second pc and use Snip. The problem is relatively easy to overcome. On my streaming pc I share a drive over the network. I have my Snip folder on this remote drive and I map the network drive in windows to, for example, drive S (you can make it whatever you want). Then I run Snip on my gaming PC from there. What this does is cause the text file to be on the streaming PC. Then in OBS on my streaming PC I just point it to that text file.

You can do the same the other way around too and share your Snip folder to the streaming PC.

**Comment by karsaidavid** [comment]
Managed to solve it with two spotify clients on both pc's using spotify's sync between devices thingy. Works like charm,thank for everyone who helped.

**Comment by GenesisFR** [comment]
> I stream to a second pc and use Snip. The problem is relatively easy to overcome. On my streaming pc I share a drive over the network. I have my Snip folder on this remote drive and I map the network drive in windows to, for example, drive S (you can make it whatever you want). Then I run Snip on my gaming PC from there. What this does is cause the text file to be on the streaming PC. Then in OBS on my streaming PC I just point it to that text file.
> 
> You can do the same the other way around too and share your Snip folder to the streaming PC.

Why didn't I think of LAN sharing, that's genius!
