### ISSUE TITLE
Album name is not exported from iTunes to Snip.txt

### ISSUE THREAD

**Issue by RovoMe** [dlrudie/Snip#444]
On the default settings with iTunes selected the album information isn't exported to Snip.txt in my case, even though the currently played song does have all of the information defined. I already tried to define `$$ul` or `$$ll` instead but this does not add the album information either.

Furthermore it would be benefitial to define an own pattern, using the given variables, to produce a desired output string, i.e. `$$t - [$$l] - $$a` and in case of absence of i.e. the album information present a default text such as `Unknown` or the like should be added.

**Comment by dlrudie** [comment]
Having a single customizable field to edit the output format has been on my list for awhile. No time though. You can still create your own custom output field just by mixing and matching the variables. Just because $$t is under track doesn't mean you can't put it under artist instead. You could technically combine them all onto one of the lines even.

The default behavior of Snip is that if the album field is empty it will just be blank. It won't say Unknown or anything, it just won't display it.
