### ISSUE TITLE
Exported files refuse to update

### ISSUE THREAD

**Issue by Baladce** [dlrudie/Snip#472]
I'm trying to use Snip as a replacement for Muxy which is now defunct. 
Basically, I'm using a music visualizer software called Kauna, which allows me to select a file for the album artwork for certain backgrounds. I used Muxy to extract the album art from Spotify, but with that dead I've tried to switch to Snip. Snip works as intended, up until the album art file is being grabbed by Kauna, at which point it stops updating automatically when I switch songs. Then my music visualizer is stuck on the first song's album art. If I shut down the music visualizer, Snip begins working as intended once more, and continues updating the album art when I switch songs on Spotify. Any ideas how to fix?  OR recommendations for a different software that can extract Spotify album art and update it when I switch songs

**Comment by GenesisFR** [comment]
Wild guess, I'd say Kauna is locking access to the album art file, which prevents Snip from updating it. I don't see any solution for this besides maybe launching Snip before Kauna, but that's again a wild guess.

**Comment by Baladce** [comment]
That was my first assumption too, I tried this :( Snip is of course launched with Admin priv. Not sure what trigger's Kauna regrabbing the file but it worked fine with Muxy before they shut it down.

**Comment by murko69** [comment]
Don't know if this is related but since the album art is called 'Snip_Artwork.jpg' no matter what it might be a cache-issue?
I'm using .php to extract and visualize info about the songs I'm playing (including the album cover) but with the image info being cached it didn't update properly on song change so I had to add a random integer, like: 
`echo '<img width="640px" height="640px" title="Album Cover" src="../spotify/Snip_Artwork.jpg?v='.rand(1,999).'">';`
I think the best thing would be if the actual album cover name already was connected to the song played and that you could perhaps fill in an 'offline-image' to show, from the start so that this wasn't needed but...

Don't know anything about Kauna nor Muxy so I don't know if this helps at all :)

**Comment by dlrudie** [comment]
@murko69 If it's your own webserver you could modify the header sent for the spotify directory to either reduce or disable the cache time. As long as the browser respects that header (and most do) then it should work okay. Although your solution also should work.

There's enough data provided currently to build something that works well too.

For example, you could set Snip to save all album artwork. The artwork filename is actually the album ID provided by Spotify. You could in turn use the metadata provided to snag the album ID and then load the album artwork straight from the saved artwork directory directly. This would prevent re-using the same filename.

As for the file not updating when Kauna is running, the only thing I can think of is it's what @GenesisFR stated. Kauna may be locking the file preventing Snip from overwriting it.
