### ISSUE TITLE
LocalHost refusing to connect 

### ISSUE THREAD

**Issue by ditZy2K** [dlrudie/Snip#489]
ran as administrator and also lets me log into Spotify but then the page just goes to this 
![image](https://user-images.githubusercontent.com/100554716/155932500-aa060a2e-c24e-45eb-8dc0-f18447305e9b.png)

and Streamlabs doesn't show anything

I've tried with iTunes and it worked perfectly but I don't have any songs on iTunes

any ideas?

**Comment by snarfle82** [comment]
I know it's been a couple months, but in case you're still having issues - 

by any chance, have you edited your hosts file (in Windows\System32\drivers\etc) to try to block spotify ads?

I ask because the method people use involves editing the hosts file, to point spotify to localhost instead of the internet based ad CDNs.   so, i was thinking something like that could be causing what you're seeing.  Keep in mind I have not looked into how the Snip/Spotify authorization works.  perhaps it always targets localhost.    just trying to help.

**Comment by ditZy2K** [comment]
> 
Hiya, I played around with my Spotify and host file awhile ago, nothing seemed to fix it until later I found out that it was refusing to connect purely because of my Kaspersky security, welp.
