### ISSUE TITLE
Snip Does Not Detect Spotify

### ISSUE THREAD

**Issue by Mythotical** [dlrudie/Snip#49]
On Windows 10, Snip does not detect that Spotify is running and a song is playing. When it finally does know Spotify is running, it continues to say No Track Playing even though I have a track playing.

**Comment by Mr-Dice** [comment]
It's not a Windows 10 issue, the issue is that the latest release of Spotify does not display the current playing track's details in the window title. Spotify version 1.0.10.107 does however. Spotify keep releasing buggy updates recently which break and remove more features than they fix or add. I'd recommend looking for a guide online to disable automatic updates, otherwise you're gonna run into the issue a lot.

**Comment by Mythotical** [comment]
Thanks, I'm looking into it now. Installed old version and looking at turning off auto update. So far it only gives me the option to update but hasn't forced me yet. *knocks on wood*

**Comment by hydrosine** [comment]
@Mr-Dice With the version you refer to, the Album Artwork capture does not work.

Just save the executable should it somehow update by accident, although it would be nice if it was made compatible with latest Spotify.

**Comment by Mythotical** [comment]
I have it working again. Honestly it updated again even with me doing what I found making 2 files, read only, etc. So I placed them where ever I saw update titles in the Spotify folder which so far so good. However, when it updated Snip worked again but upon restarting it stopped working. If I knew what program to use I could probably modify these small apps myself and then submit fixes.

**Comment by dlrudie** [comment]
I've been using Snip on Windows 10 and it works just fine. As long as Spotify keeps the artist and track in the window title Snip will work.

**Comment by Mythotical** [comment]
Ok so for the fix to work I found, you must use a version prior to 1.0 of Spotify otherwise the files you create will not stop it from updating on Windows 10.
