### ISSUE TITLE
Snip not updating songs

### ISSUE THREAD

**Issue by djjulzen** [dlrudie/Snip#505]
I know this hasn't been updated since 2019...
As a streamer and song information not getting updated from Spotify is really irritating that I had no choice but to close snip all together on that stream.
I kept refreshing it, pausing and unpausing, it fixes it here and there but then continues to not update but stay on the previous song.
I get freeware even has its own issues but still
Nobody wants their stream displaying the wrong song information (example being the previous song when its already playing the next song)
Please UPDATE your software to improve real time updates through Spotify

**Comment by dlrudie** [comment]
There's right ways to approach things and wrong ways to approach things. This is the wrong way. I do not work for you or anyone else. This is just a side hobby of mine. I do not get paid to create or maintain this software. I have a full-time job and other hobbies that take priority. I work on this when I can and when I have inspiration to. I understand there are issues with the software. The code is readily available for anyone that would like to fix and tackle those problems themselves.

Snip in its current form functions and works for most people. There are over 40,000 people concurrently using it each and every day per Spotify's developer portal. The overall issues being submitted here are low compared to the total users. Personally, it works for me and doesn't have any issues.

For what it's worth I am working on a whole new version. The progress is slow because, again, this is just a side hobby.

**Comment by thealzhe** [comment]
Hi.

The maneuver used by the above person is not very friendly or even human. But I've come to tell you personally that I have exactly the same problems. Snip does not update any sound. I'm on a single screen PC, Spotify is open but my game is in fullscreen with the chat overlay. So I don't check my sounds on the screen very often, but my viewers confirm it: it doesn't synchronize after 2-3 songs.

It's impossible for me to update the file except by changing the music, all in the middle of the live and from the middle of my competitive/ranked games.

I have Spotify Premium and all, I don't see any log file so I don't know how to help debugging but I hope one day this glitch will be solved.

Hope this will be fixed as soon as you find the problem.

King regards,
