### ISSUE TITLE
Snip can't run.

### ISSUE THREAD

**Issue by ericmay2111** [dlrudie/Snip#60]
I recently downloaded Snip v5.1.0 and unzipped the file. Then when i click the Snip.exe file something pops up on my computer and says "This app can't run on your PC." It says to find a version that works check with software publisher. I don't know if there is an easy way to do this. I don't know a ton about computers. I have windows 10. My computer isn't even a year old so I don't know what is wrong. If there is some other information you need I will happily provide it.

Thanks

**Comment by ghostmansk** [comment]
I have the same problem but windows 8.1

**Comment by 12jpayne** [comment]
@ericmay2111 @ghostmansk  hi 
i had that issue so i removed the files off my computer and just downloaded them into my documents. then i went into my documents right clicked on the file and extracted it. then i clicked on the snip file and then on the snip.exe file you need to right clikck and run as administraitor.
it should work after that

josh
thanks

**Comment by ericmay2111** [comment]
Josh, I did exactly what you said and when I click run as administrator it still pops up and says "This app can't run on your PC."

**Comment by 12jpayne** [comment]
@ericmay2111 
hi
ok then I don't know what issues is

sorry I couldn't help

josh

**Comment by ericmay2111** [comment]
It's alright. I appreciate you trying to help Josh. Thank you.

**Comment by dlrudie** [comment]
Can you provide me details about your system? OS, CPU, 32-bit/64-bit, etc, etc, etc?

**Comment by derfifi** [comment]
@dlrudie I have Windows 10 64bit, i74790k & gtx970 sli.  Pls fix that

**Comment by dlrudie** [comment]
Is this still an issue for some of you? Do you have .NET Framework 4.5 installed?

**Comment by Drakma** [comment]
I get the following error when trying to run this on Windows 10 Home.  It worked on a previous machine, however it doesn't work on a fresh build.

.NET 4.5 is installed

I get an "Invalid JSON String" error message at startup.

Details of the error are below

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Runtime.Serialization.SerializationException: Invalid JSON string
   at SimpleJson.SimpleJson.DeserializeObject(String json)
   at Winter.Spotify.Update()
   at Winter.Snip.TimerScanMediaPlayer_Tick(Object sender, EventArgs e)
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.127.1 built by: NETFXREL3STAGE
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
Snip
    Assembly Version: 5.1.0.0
    Win32 Version: 5.1.0.0
    CodeBase: file:///C:/Users/Debra/Desktop/Snip/Snip.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.93.0 built by: NETFXREL2STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.CSharp
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp/v4.0_4.0.0.0__b03f5f7f11d50a3a/Microsoft.CSharp.dll
----------------------------------------
System.Web
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.114.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by labrador936** [comment]
my os win7 pro i can't run the Snip.exe , it gives me an error msg saying : it's not a valid win32 application please any help!
