### ISSUE TITLE
Snip v5.1.0 Invalid JSON string

### ISSUE THREAD

**Issue by NeroChaos1** [dlrudie/Snip#79]
Snip keeps popping up with "Invalid JSON string" whenever I try to play a track in Spotify. It's been plaguing me quite a bit since I first got the program a few days ago.

**Comment by MakerTim** [comment]
Can confirm, use the program almost 6months now, this issue is new since this week for me;

**Comment by haxxprox** [comment]
same problem here with    v.5.1.0.7

https://www.reddit.com/r/software/comments/41ulcz/i_need_help_with_a_program_json_string_in/

**Comment by dlrudie** [comment]
I will look at this first thing when I get off of work tonight.

**Comment by itsZdan** [comment]
spotify got updated therefor creating the error :(
any idea when you will fix it dlrudie? so that i know if i push my stream back or not

thx for a great app

**Comment by dlrudie** [comment]
I get off of work in about 5 hours and I'll take a look at it then.

**Comment by Brian4321** [comment]
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Runtime.Serialization.SerializationException: Invalid JSON string
   at SimpleJson.SimpleJson.DeserializeObject(String json)
   at Winter.Spotify.Update()
   at Winter.Snip.TimerScanMediaPlayer_Tick(Object sender, EventArgs e)
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.96.0 built by: NETFXREL2STAGE
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
Snip
    Assembly Version: 5.1.0.0
    Win32 Version: 5.1.0.0
    CodeBase: file:///C:/Users/Brian/Desktop/Programs/Streaming/Snip/Snip.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.93.0 built by: NETFXREL2STAGE
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.CSharp
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.33440
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp/v4.0_4.0.0.0__b03f5f7f11d50a3a/Microsoft.CSharp.dll
----------------------------------------
System.Web
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by pmatias** [comment]
This started happening to me today, I don't know if it helps but it started after the latest Spotify upgrade.

**Comment by dlrudie** [comment]
It looks like they changed their API.

When you pull up the JSON URL now it says that the API has been deprecated and there's a new API.
https://developer.spotify.com/web-api/migration-guide/

However, this site is hardly loading and is very slow. Hopefully it will clear up by the time I get home. Meanwhile I'll do some research on it here at work to get a head start.

**Comment by Brian4321** [comment]
Please compile and release 5.1.1 or w/e~

**Comment by dlrudie** [comment]
Calm your tits, sir; this is being worked on.

**Comment by Brian4321** [comment]
I asked nicely and you responded with such a rude statement, I know it's being worked on, However I only asked if you could compile it since Its unusable till then.

**Comment by dlrudie** [comment]
It wasn't intended as being rude at all.

I haven't compiled a release yet because I'm still working on it. I'm testing all functions to make sure everything works correctly. Had I released it after the initial commit album art would have not worked and caused a crash. No sense in releasing something prematurely.

It will be compiled and uploaded within the hour.

**Comment by pmatias** [comment]
Dude take your time, you're doing an amazing job!

**Comment by dlrudie** [comment]
https://github.com/dlrudie/Snip/releases/latest

**Comment by itsZdan** [comment]
thank you

**Comment by haxxprox** [comment]
thank you so much keep up the good work :)

**Comment by pmatias** [comment]
I can confirm it's working again.

Thanks so much for your work!!!
