### ISSUE TITLE
[Spotify] OBS Multiplatform doesn't read the text file if I pause music.

### ISSUE THREAD

**Issue by warble3** [dlrudie/Snip#86]
I checked the text file and it seems to be updating when I pause (emptying file) and play (artist and song are placed in the file) but OBS no longer seems to present the file information once I have paused Spotify at all. It works before this, basically if I restart OBS then the information will start showing again.

I am using 5.30 on Windows 10 with the latest version of Spotify. OBS version 0.13.1 (64)

Everything works if I disable "empty file if no track playing" but ideally I would not to enable this option.

**Comment by dlrudie** [comment]
This is an issue you would need to take up with OBS. Perhaps they are not checking if the file was modified or re-reading it.

**Comment by warble3** [comment]
Just a thought. A way around this would be an output format option for when the music is paused. Instead of just empty or artist information. Then the user could just put "Paused" in the file.
  
By the way, do you play APB? I think I have shot at or with you at some point.

**Comment by dlrudie** [comment]
The problem is that Snip is operating as designed. If something else fails to read a text file that's on that program.

Snip does have an option to fill the text file with other text. The option to empty the file is enabled by default. If you disable it then it will say that the player is paused, not running, stopped, etc.
